import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Extract package names from an `npm install foo bar baz` command string.
 * Returns deps in the order they appear, ignoring the `npm install` prefix
 * and any trailing flags.
 */
export function parseDepsFromInstall(install: string): string[] {
  const tokens = install.trim().split(/\s+/);
  // Drop "npm install" / "npm i" / "yarn add" / "pnpm add" prefix.
  let i = 0;
  if (tokens[i] === "npm" || tokens[i] === "yarn" || tokens[i] === "pnpm") i++;
  if (
    tokens[i] === "install" ||
    tokens[i] === "i" ||
    tokens[i] === "add"
  )
    i++;
  return tokens.slice(i).filter((t) => t && !t.startsWith("-"));
}

const TSX_VERSION = "^4.19.0";
const TYPESCRIPT_VERSION = "^5.7.0";
const NODE_TYPES_VERSION = "^22.0.0";

/**
 * Pinned versions for packages whose `latest` tag breaks the template imports.
 * langchain v1 removed the `langchain/agents` subpath; templates target v0.3.
 * @langchain/* packages are pinned in lockstep so resolution stays internally
 * consistent.
 */
const PINNED_VERSIONS: Record<string, string> = {
  langchain: "^0.3.0",
  "@langchain/core": "^0.3.0",
  "@langchain/openai": "^0.3.0",
  "@langchain/community": "^0.3.0",
  "@langchain/langgraph": "^0.2.0",
  zod: "^3.24.0",
};

function resolveVersion(pkg: string): string {
  return PINNED_VERSIONS[pkg] ?? "latest";
}

/**
 * Write a package.json suitable for a scaffolded TS agent or service.
 * Skips the file if one already exists in cwd.
 *
 * `entryFile` is the entry script (e.g. "agent.ts" or "service.ts").
 * `runCommand` is the `start` script (e.g. "zynd agent run").
 */
export function writeTsPackageJson(opts: {
  cwd: string;
  name: string;
  deps: string[];
  entryFile: string;
  runCommand: string;
}): boolean {
  const pkgPath = path.join(opts.cwd, "package.json");
  if (fs.existsSync(pkgPath)) return false;

  // De-dupe and ensure zyndai + dotenv + zod are present.
  // Every scaffolded entry file does `import "dotenv/config"` and the
  // payload.ts schema imports zod, so both ship regardless of framework.
  const seen = new Set<string>();
  const orderedDeps: string[] = [];
  for (const d of ["zyndai", "dotenv", "zod", ...opts.deps]) {
    if (!seen.has(d)) {
      seen.add(d);
      orderedDeps.push(d);
    }
  }

  const dependencies: Record<string, string> = {};
  for (const d of orderedDeps) dependencies[d] = resolveVersion(d);

  const pkg = {
    name: opts.name,
    version: "0.1.0",
    private: true,
    description: `${opts.name} — generated by zynd`,
    type: "module",
    scripts: {
      start: opts.runCommand,
      dev: `tsx watch ${opts.entryFile}`,
      typecheck: "tsc --noEmit",
    },
    dependencies,
    devDependencies: {
      tsx: TSX_VERSION,
      typescript: TYPESCRIPT_VERSION,
      "@types/node": NODE_TYPES_VERSION,
    },
  };

  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
  return true;
}

/**
 * Minimal tsconfig.json for tsx + type checks. Skips if already present.
 */
export function writeTsConfig(cwd: string): boolean {
  const tsconfigPath = path.join(cwd, "tsconfig.json");
  if (fs.existsSync(tsconfigPath)) return false;
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "Bundler",
      esModuleInterop: true,
      strict: true,
      skipLibCheck: true,
      resolveJsonModule: true,
      allowImportingTsExtensions: false,
      noEmit: true,
    },
    include: ["**/*.ts"],
    exclude: ["node_modules", "dist"],
  };
  fs.writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2) + "\n");
  return true;
}

/**
 * Write a .gitignore tailored for a TS scaffold. Skips if one already exists.
 */
export function writeGitignore(cwd: string): boolean {
  const giPath = path.join(cwd, ".gitignore");
  if (fs.existsSync(giPath)) return false;
  const lines = [
    "node_modules/",
    "dist/",
    ".env",
    ".env.local",
    "*.log",
    ".DS_Store",
    "",
  ];
  fs.writeFileSync(giPath, lines.join("\n"));
  return true;
}
